## file.dep.tsk.toml -*- mode: toml-mode -*-
# reminders:
# action = [{do= "basic", args=[]}]
# cli    = [{name="", type="str", prefix="-", default="", desc="", positional=false}]

doot_version = "1.1"

[[state]]     # Key=vals for all tasks

[[locations]]
target = "file::>./is-there.txt"

[tasks]

[[tasks."file.dep"]]
name        = "top"
doc         = ["An example of file dependencies"]
depends-on  = ["file.dep::_.yes"]
actions = [
    {do="log", msg="The file now exists"},
]
cleanup = [
    {do="log", msg="Deleting File"},
    {do="delete!", args=["{target!p}"]},
]       

[[tasks."file.dep"]]
disabled             = false
name                 = "_.no"
doc                  = ["This shouldn't run, because the file doesn't exist"]
depends-on           = ["file::>./not-there.txt"]
actions = [
    {do="log", msg="This should not be printed, because ./not-there.txt should not exist"},
]

[[tasks."file.dep"]]
name                 = "_.yes"
doc                  = ["this should run"]
depends-on           = ["file::>./is-there.txt"]
actions              = [{do="log", msg="File Exists"}]


[[tasks."file.dep"]]
name                  = "_.make.file"
doc                   = ["this will create file.deps.op's file dependency"]
val                   = "some simple data"
actions               = [
    {do="log", msg="Making File"},                        
    {do="write!", from_="val", to="./is-there.txt"}
]
required-for          = ["file::>./is-there.txt"]
