# -*- mode:conf-toml; -*-
[settings.general]
task                     = { sleep = 0.2 }
subtask                  = { sleep = 1 }
batch                    = { sleep = 1 }
notify                   = { say-on-exit = false }
loaders                  = {commands = "default", task = "default", parser = "default"}
location_check           = { make_missing = true, print_levels = { head="INFO", action="WARN", execute="WARN" } }

[settings.globbing]
ignores  = ['.git', '.DS_Store', "__pycache__"]

[logging]
stream  = { level="WARN",  allow=["doot"], format="{levelname:<8} : {message}", colour=true }
file    = { level="DEBUG", allow=["doot"], format="{levelname:<8} : {message:<20} :|: (module:{module} line:{lineno} fn:{funcName})" }
printer = { level="DEBUG", colour=true }

[commands]
clean = { locs = ["{temp}"] }


[[locations]]
stubs = "stubs"
temp  = ".temp"
data  = "data"
