# -*- mode:toml; -*-

[startup]
doot_version  = "1.1"
loaders       = { commands="default", task="default", parser="default" }
sources       = { tasks=[".tasks"], code=[] }
empty_cmd     = ["run", "state::top"]

[startup.plugins]
# Allows for defining aliases
command        = { tasks="doot.cmds.list_cmd:ListCmd"}

[shutdown]
notify           = { speak=false } # success_msg="", fail_msg=""
defaulted_values = { write=false, path=".defaulted_values.toml" }

[settings.commands]

[settings.commands.run]
tracker     = "default"
runner      = "default"
reporter    = "default"
report-line = []

[settings.commands.list]
hide = []
aliases = { tasks=[] }

[logging]
stream  = { level="user",   filter=[],             target="stdout", format="{levelname:<8} : {message}"  }
file    = false
printer = { level="WARNING", colour=true,           target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }

[logging.extra]

[[locations]]

[[global]]
global_value = "bloo"

[[tasks.state]]
name        = "top"
depends_on  = ["state::_.local", "state::_.global" ]

[[tasks.state]]
name     = "_.local"
a_value  = "blah"
actions  = [
    {do="log", msg="----------------"},
    {do="log", msg="Getting the value from local state: {a_value}."},
    {do="log", msg="(It Should be 'blah'.)"},
]

[[tasks.state]]
name     = "_.global"
actions  = [
    {do="log", msg="----------------"},
    {do="log", msg="Getting the value from local state: {global_value}."},
    {do="log", msg="(It Should be 'bloo'.)"},
]
