# -*- mode:toml; -*-
# This doot config runs tasks
# depending on whether pre-commit env vars are defined

[startup]
# The version this config file works with:
doot_version          = "1.1"
loaders               = { commands="default", task="default", parser="default" }
sources               = { tasks=[".tasks"], code=[] }
skip_default_plugins  = false
skip_plugin_search    = false
empty_cmd             = ["run", "example::env.checked"]


[settings.commands]
[settings.commands.run]
tracker         = "default"
runner          = "default"
reporter        = "default"
location_check  = { active=true, make_missing=false, strict=true }
sleep           = { task=0.2, subtask=1, batch=1 }

[logging]
file = false
extra.jgdv = false

[logging.stream]
level     = "user"
filter    = []
target    = ["stdout"]
format    = "{levelname:<8} : {message}"

[logging.printer]
level         = "WARNING"
colour        = true
target        = ["stdout"] 
format        = "{message}"
filename_fmt  = "doot_printed.log"


[[locations]]

[[tasks.example]]
name        = "env.checked"
depends_on  = [
    {do="log", msg="Checking for env var: DOOT_TEST"},
    {do="doot.workflow.actions.control_flow.control_flow:EnvVarCheck", args=["DOOT_TEST"], fail=true},
]
actions  = [{do="log", msg="DOOT_TEST was found in the environment"}]


