# -*- mode:toml; -*-


[startup]
doot_version         = "1.1"
loaders              = { commands="default", task="default", parser="default" }
sources              = { tasks=[".tasks"], code=[] }
empty_cmd = ["run"]

[logging]
file = false
extra.jgdv = false

[logging.stream]
disabled  = false 
level     = "user"
filter    = []
target    = ["stdout"]
format    = "{levelname:<8} : {message}"


[logging.printer]
disabled      = false
level         = "WARNING"
colour        = true
target        = ["stdout"] 
format        = "{message}"
filename_fmt  = "doot_printed.log"

[[locations]]

[[tasks.example]]
name     = "postbox"
actions  = [
# Put stuff in the postbox
# Get it out
# print it
]
