# -*- mode:toml; -*-
[startup]
doot_version  = "1.1"
loaders       = { commands="default", task="default", parser="default" }
sources       = { tasks=[".tasks"], code=[] }
empty_cmd     = ["run", "cli.args::top"]

[logging]
# Standard loggers. See jgdv.logging.LoggerSpec.
# Additional Level aliases: detail=debug, trace=info, user=warning
stream  = { level="user",   filter=[],             target="stdout", format="{levelname:<8} : {message}"  }
file    = false
printer = { level="WARNING", colour=true,           target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }

[[tasks."cli.args"]]
name    = "top"
doc     = ["call with 'doot example::cli.args -arg {a string}'"]
cli     = [{name="-custom", type="str", default="blah"}]
actions = [
    {do="log", msg="This is a task that uses a cli arg"},
    {do="log", msg="The CLI Arg was: {custom} (default is 'blah')"},
    {do="log", msg="Change the arg by calling:"},
    {do="log", msg="doot cli.args::top -custom 'some other value'"},
]
