# -*- mode:toml; -*-
# This demonstrates how one task can depend on another task

[startup]
doot_version  = "1.1"
loaders       = { commands="default", task="default", parser="default" }
sources       = { tasks=["."], code=[] }
empty_cmd     = ["run", "task.dep::top"]

[logging]
# Standard loggers. See LoggerSpec.
stream   = { level="WARN", filter=[],  target="stdout",   format="{levelname:<8} : {message}"  }
file     = false
printer  = { level="WARNING", colour=true, target=["stdout"], format="{message}"}

[[locations]]
# Note how the task group is more complex, by wrapping in quotes

[[tasks."task.dep"]]
name        = "top"
prefix      = "top"
doc         = ["An example of transitive task requirements"]
depends-on  = ["task.dep::_.mid"]
setup       = [
    {do="log", msg="Task: {_task_name}"},
    {do="log", msg="3.a the Top Task's setup"},
]
actions     = [
    {do="log", msg="3.b The Top Task, which depends on the middle."},
]
cleanup = [
    {do="log", msg="3.c The Top Task's cleanup"}, 
]

[[tasks."task.dep"]]
name        = "_.mid"
prefix      = "mid"
depends-on  = ["task.dep::_.bottom"]
actions     = [
    {do="log", msg="Task: {_task_name}"},
    {do="log", msg="2. Middle task, which depends on the bottom."},
    {do="log", msg="--------------------------"},
]

[[tasks."task.dep"]]
name          = "_.bottom"
prefix        = "bot"
required-for  = ["task.dep::_.mid"]
actions       = [
    {do="log", msg="Task: {_task_name}"},
    {do="log", msg="1. The Bottom task, which doesn't depend on anything."},
    {do="log", msg="--------------------------"},
]
