# -*- mode:toml; -*-

[startup]
# The version this config file works with:
doot_version  = "1.1"
loaders       = { commands="default", task="default", parser="default" }
sources       = { tasks=[".tasks"], code=[] }
empty_cmd     = ["stub", "test::task.stub"]

# Setup output stream, file logging, and printing
# See jgdv.logging for details
[logging]
file = false

[logging.stream]
level  = "user"
filter = []
target = "stdout"
format = "{levelname:<8} : {message}"

[logging.printer]
level         = "WARNING"
colour       = true
target       = ["stdout"]
format       = "{message}"
filename_fmt = "doot_printed.log"

