# -*- mode:toml; -*-

[startup]
doot_version          = "1.1"
loaders               = { commands="default", task="default", parser="default" }
sources               = { tasks=[".tasks"], code=[] }
skip_default_plugins  = false
skip_plugin_search    = false
empty_cmd             = ["run", "example::+.implicit"]

[startup.plugins]
# Allows for defining aliases
command        = { tasks="doot.cmds.list_cmd:ListCmd"}

[shutdown]
notify           = { speak=false } # success_msg="", fail_msg=""
defaulted_values = { write=false, path=".defaulted_values.toml" }

[settings.commands]

[settings.commands.run]
tracker     = "default"
runner      = "default"
reporter    = "default"
report-line = []

[settings.commands.list]
hide     = []
aliases  = { tasks=[] }

[logging]
file = false

[logging.stream]
level   = "user"
filter  = []
target  = "stdout"
format  ="{levelname:<8}  : {message}"

[logging.printer]
level        = "WARNING"
colour       = true
target       = ["stdout"]
format       = "{message}"
filename_fmt = "doot_printed.log"

[logging.extra]

[[locations]]

[[tasks.example]]
name         = "+.implicit"
doc          = ["A job declared using +. as its name prefix"]
actions      = [
    {do="log", msg="Entering Job"},
    {do="dootle.jobs.queue:JobQueueAction",  args=["example::_.simple", "example::_.simple", "example::_.simple"]},
    {do="log", msg="Queued Subtasks"},
]
head-actions = [{do="log", msg="Head Action"}]
cleanup      = [{do="log", msg="Cleaning up"}]


[[tasks.example]]
name         = "_.simple"
actions      = [
    {do="log", msg="SubTask. {_task_name}"}
]
