# -*- mode:toml; -*-

[startup]
doot_version          = "1.1"
loaders               = { commands="default", task="default", parser="default" }
sources               = { tasks=[".tasks"], code=[] }
skip_default_plugins  = false
skip_plugin_search    = false
empty_cmd             = ["run", "example::+.implicit"]

[logging]
file = false

[logging.stream]
level   = "WARNING"
filter  = []
target  = "stdout"
format  ="{levelname:<8}  : {message}"

[logging.printer]
level        = "WARNING"
colour       = true
target       = ["stdout"]
format       = "{message}"
filename_fmt = "doot_printed.log"

[logging.extra]
jgdv = false

[[locations]]

[[tasks.example]]
name         = "+.implicit"
doc          = ["A job declared using +. as its name prefix"]
actions      = [
    {do="log", msg="Entering Job. Queuing 1 new Task."},
    {do="dootle.jobs.expand:JobQueueAction",  args=["example::_.simple"]},
    {do="log", msg="Queued Subtasks"},
    {do="log", msg="----------------"},
]
head-actions = [
    {do="log", msg="Job Head"},
    {do="log", msg="----------------"},
]
cleanup      = [
    {do="log", msg="Cleaning up"},
    {do="log", msg="----------------"},
]


[[tasks.example]]
name         = "_.simple"
actions      = [
    {do="log", msg="SubTask. {_task_name}"},
    {do="log", msg="----------------"},
]
