
##-- locs
[[locations]]
temp               = ".temp"
logs               = ".logs"
src                = "doot"
docs               = "docs"
data               = "data"
codegen            = "{src}/_codegen"
listings_out       = "{build}/listing"
lint_out           = "{build}/lint"
bots               = ".bots"
build              = "doot_build"

[[locations]] # Backup
backup_root        = "/Volumes/BackupSD/"
images_backup      = "/Volumes/BackupSD/Pictures"
movies_backup      = "/Volumes/BackupSD/Movies"
pdf_backup         = "/Volumes/BackupSD/Library/pdf_library"
pdf_summary_backup = "/Volumes/BackupSD/Library/summary"
thread_backup      = "/Volumes/BackupSD/Library/twitter_threads"

[[locations]] # Watch Directories
bibtex             = "~/github/jgrey4296.github.io/resources/bibliography"
downloads          = "~/Downloads"
desktop            = "~/Desktop"
dropbox            = "~/Dropbox/docs"
bibtex_working     = "/Volumes/documents/in_progress_pdfs/Current/"
firefox            = "~/Library/ApplicationSupport/Firefox"

[[locations]] # libraries
bookmarks          = "~/github/jgrey4296.github.io/resources/bookmarks"
tags               = "~/github/jgrey4296.github.io/resources/tags"
orgs               = "~/github/jgrey4296.github.io/orgfiles"
thread_library     = "/Volumes/documents/twitter_threads"
pdfs               = "/Volumes/documents/pdf_library"
movies             = "/Users/johngrey/Movies"
images             = "/Volumes/documents/DCIM"
github             = "~/github"
git_libs           = "~/github/_libs"

[[locations]] # library locations
bookmarks_total = "~/github/jgrey4296.github.io/resources/bookmarks/total.bookmarks"

[[locations]] # output
pdf_summary        = "/Volumes/documents/in_progress_pdfs/pdflib_automations/total_bib"
maintain           = "/Volumes/documents/github/__configs/terminal/maintenance"

[[locations]] # Android
local_push         = "/Volumes/documents/pdf_library"
local_pull         = "/Volumes/documents/android_test_pull"

[[locations]] # bibtex bot locations
bib_blacklist   = "{bots}/bibtex_blacklist"
bib_compile_tex = "{bots}/bib_compile_template.tex"
bib_success     = "{bots}/log.bib_success"
bib_fail        = "{bots}/log.bib_fail"
bib_style       = "{bots}/jg_custom.bst"

[[locations]] # image bot locations
image_whitelist = "{bots}/dcim_whitelist"
image_blacklist = "{bots}/resolution_blacklist"
image_temp      = "{bots}/conversion_temp"
bib_stub_file   = "~/github/jgrey4296.github.io/resources/todo.bib"
secrets         = "~/.secrets/bkmkorg.toml"

##-- end locs

[tasks]

[[tasks.mail]]
name                 = "update"
version              = "0.1"                # <str>
ctor                 = "basic"              # <str>
doc                  = []                   # <list[str]>
actions              = []                   # <list[Any]>
runs_before          = []                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = []                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = ""                   # <int>
tasker_updates       = []                   # <list[str]>
print_level          = ""                   # <str>
flags                = [ "TASK" ]           # <TaskFlags>


[[tasks.time]]
name                 = "report"
version              = "0.1"                                                                          # <str>
ctor                 = "task"                                                                         # <str>
doc                  = ["Announce the Current Time"]                                                  # <list[str]>
flags                = [ "TASK" ]                                                                     # <TaskFlags>
actions              = [{ctor = "doot.actions.time_action:TimeAction", args=[]}]                      # <list[Any]>
