[[tasks.latex]]
name                 = "build"
version              = "0.1"                # <str>
ctor                 = "basic"              # <str>
doc                  = []                   # <list[str]>
actions              = []                   # <list[Any]>
runs_before          = []                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = []                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = ""                   # <int>
tasker_updates       = []                   # <list[str]>
print_level          = ""                   # <str>
flags                = [ "TASK" ]           # <TaskFlags>

[[tasks.bibtex]]
name                 = "group"
version              = "0.1"                # <str>                
ctor                 = "basic"              # <str>
doc                  = []                   # <list[str]>
actions              = []                   # <list[Any]>
runs_before          = []                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = []                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = ""                   # <int>
tasker_updates       = []                   # <list[str]>
print_level          = ""                   # <str>
flags                = [ "TASK" ]           # <TaskFlags>

[[tasks.latex]]
name                 = "head"
version              = "0.1"                # <str>
ctor                 = "basic"              # <str>
doc                  = []                   # <list[str]>
actions              = []                   # <list[Any]>
runs_before          = []                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = []                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = ""                   # <int>
tasker_updates       = []                   # <list[str]>
print_level          = ""                   # <str>
flags                = [ "TASK" ]           # <TaskFlags>


[[tasks.bibtex]]
name                 = "clean"
version              = "0.1"                # <str>
ctor                 = "basic"              # <str>
doc                  = []                   # <list[str]>
actions              = []                   # <list[Any]>
runs_before          = []                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = []                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = ""                   # <int>
tasker_updates       = []                   # <list[str]>
print_level          = ""                   # <str>
flags                = [ "TASKER" ]           # <TaskFlags>

[[tasks.bibtex]]
name                 = "stub"
version              = "0.1"                # <str>
ctor                 = "basic"              # <str>
doc                  = []                   # <list[str]>
actions              = []                   # <list[Any]>
runs_before          = []                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = []                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = ""                   # <int>
tasker_updates       = []                   # <list[str]>
print_level          = ""                   # <str>
flags                = [ "TASKER" ]           # <TaskFlags>
