
[[tasks.posting]]
name                 = "mastodon-image"
version              = "0.1"                # <str>
ctor                 = "basic"              # <str>
doc                  = []                   # <list[str]>
actions              = []                   # <list[Any]>
runs_before          = []                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = []                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = ""                   # <int>
tasker_updates       = []                   # <list[str]>
print_level          = ""                   # <str>
flags                = [ "TASK" ]           # <TaskFlags>

[[tasks.posting]]
name                 = "mastodon-bib"
version              = "0.1"                # <str>
ctor                 = "basic"              # <str>
doc                  = []                   # <list[str]>
actions              = []                   # <list[Any]>
runs_before          = []                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = []                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = ""                   # <int>
tasker_updates       = []                   # <list[str]>
print_level          = ""                   # <str>
flags                = [ "TASK" ]           # <TaskFlags>
