
[[tasks.time]]
name                 = "report"
version              = "0.1"                                                                          # <str>
ctor                 = "task"                                                                         # <str>
doc                  = ["Announce the Current Time"]                                                  # <list[str]>
flags                = [ "TASK" ]                                                                     # <TaskFlags>
actions              = [{ctor = "doot.actions.time_action:TimeAction"}]                               # <list[Any]>

[[tasks.mastodon]]
name    = "test"
version = "0.1"
ctor    = "dootle.tasks.mastodon:MastodonPoster"
doc     = ["Post to Mastodon"]
actions = [ {ctor="dootle.tasks.mastodon:config_text", args=["another test, keep ignoring it"]} ]

[[tasks.interact]]
name    = "test"
version = "0.1"
ctor    = "task"
actions = [ {ctor="doot.actions.shell_action:DootInteractiveAction", args=["python", "-i"], inState = [], outState = []} ]

[[tasks.test]]
name = "verify"
ctor = "task"
actions = [ {ctor="basic"} ]
