[[locations]]
backup = "{temp}/backup"

[[tasks.backup]]
name                       = "head"
version                    = "0.1"                # <str>
ctor                       = "shadow"            # <type>
clean_locs                 = ["{backup}"]
exts                       = [".bib"]                      # <list[str]>
head_task                  = "backup::_finish"
recursive                  = true                         # <bool>
roots                      = ["{data}"]                    # <list[str|pl.Path]>  Places the globber will start
shadow_root                = "{backup}"
sub_task                   = "backup::_body"               # <task_iden>

[[tasks.backup]]
name                 = "_body"
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
print_levels          = { execute="WARN", action="WARN" }
actions              = [
                     {do="dir!", args=["{shadow_path}"] },
                     {do="backup!", source="fpath", dest="{shadow_path}/{fname}"}
]                   # <list[Any]>


[[tasks.backup]]
name                 = "_finish"
version              = "0.1"                # <str>
ctor                 = "task" # <type>
actions              = [
                     # {do="shell", args=["fdfind", "\\.bib", "{backup}"] },
                     {do="doot.actions.postbox:SummarizePostAction"},
]                   # <list[Any]>
