[[locations]]
mastodon_secrets = "~/.config/secrets/bots/bkmkorg.toml"
image_temp       = "{temp}/images/"

[[tasks.mast]]
name                 = "basic"
version              = "0.1"                # <str>
ctor                 = "task" # <type>
doc                  = ["Task   : MastodonPoster v0.1", "The Simplest Task"] # <list[str]>
actions              = [
                     { ctor = "dootle.mastodon.actions:MastodonSetup" },
                     { ctor = "dootle.mastodon.actions:set_text", args=["blah"] },
                     { ctor = "dootle.mastodon.actions:MastodonPost" },
]                   # <list[Any]>
runs_before          = []                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = []                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = 10                   # <int>
print_level          = "INFO"               # <str>
flags                = [ "TASK" ]           # <TaskFlags>
