[[locations]]
mastodon_secrets = "~/.config/secrets/bots/bkmkorg.toml"
image_temp       = "{temp}/images/"

[[tasks.mast]]
name                 = "basic"
version              = "0.1"                # <str>
ctor                 = "task" # <type>
actions              = [
                     { do= "dootle.mastodon.actions:MastodonSetup" },
                     { do= "addState", text="blah"},
                     { do= "dootle.mastodon.actions:MastodonPost", from_="text" },
]                   # <list[Any]>
runs_before          = []                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = []                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = 10                   # <int>
flags                = [ "TASK" ]           # <TaskFlags>
