
[[tasks.order]]
name                 = "_simple"
version              = "0.1"                # <str>
ctor                 = "doot.task.base_task:DootTask" # <type>
actions              = []                   # <list[Any]>
runs_before          = ["order::post"]                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = ["order::_pre"]                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = 10                   # <int>
flags                = [ "TASK" ]           # <TaskFlags>


[[tasks.order]]
name                 = "_pre"
version              = "0.1"                # <str>
ctor                 = "doot.task.base_task:DootTask" # <type>
actions              = []                   # <list[Any]>
runs_before          = ["order::post"]                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = []                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = 10                   # <int>
flags                = [ "TASK" ]           # <TaskFlags>

[[tasks.order]]
name                 = "post"
version              = "0.1"                # <str>                
ctor                 = "doot.task.base_task:DootTask" # <type>
actions              = []                   # <list[Any]>
runs_before          = []                   # <list[DootTaskArtifact | pl.Path | str]>
runs_after           = ["order::_pre", "order::_simple"]                   # <list[DootTaskArtifact | pl.Path | str]>
priority             = 10                   # <int>
flags                = [ "TASK" ]           # <TaskFlags>
