[[tasks.example]]
name                 = "local.code"
version              = "0.1"                # <str>
ctor                 = "task" # <type>
doc                  = ["An example of importing local code for an action"] # <list[str]>
actions              = [
                     # { do="tasks_code.basic:simple"},
                     { do="addFn", fn="tasks_code.basic:simple", outState=["fn"] },
                     { do="tasks_code.basic:caller", fn="fn", inState=["fn"] },
]                   # <list[Any]>
