[[tasks.walker]]
name                       = "filtered"
version                    = "0.1"                                # <str>
ctor                       = "walker"                             # <type>
exts                       = [".bib"]                             # <list[str]>
roots                      = ["{data}"]                           # <list[str|pl.Path]>  Places the globber will start
filter_fn                  = "tasks_code.basic:glob_filter"
recursive                  = true
sub_task                   = "globs::_simple"
head_task                  = "globs::_fin"
print_levels               = {head="INFO"}



[[tasks.walker]]
name                 = "_simple"
version              = "0.1"                # <str>
ctor                 = "task" # <type>
print_levels         = {head="INFO", action="WARN", execute="INFO"}
actions              = [
                     { do="log", msg="Value: {fname}"}
]                   # <list[Any]>

[[tasks.walker]]
name                 = "_fin"
version              = "0.1"                # <str>
ctor                 = "task" # <type>
print_levels         = {head="INFO"}
actions              = [
                     { do="log", msg="Finished Filtered Glob"}
]                   # <list[Any]>

