# -*- mode:toml; -*-
[startup]
doot_version  = "1.1"
loaders       = { commands="default", task="default", parser="default" }
sources       = { tasks=[".tasks"], code=["."] }
empty_cmd     = ["run", "example::action"]

[logging]
# Standard loggers. See jgdv.logging.LoggerSpec.
# Additional Level aliases: detail=debug, trace=info, user=warning
stream  = { level="WARNING",   filter=[],             target="stdout", format="{levelname:<8} : {message}"  }
file    = false
printer = { level="WARNING", colour=true,           target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }
extra.jgdv = false

[tasks]

[[tasks.example]]
name                 = "action"
doc                  = ["An example of importing local code for an action"] 
actions              = [
   # By using a coderef (see jgdv) as the 'do' value, the reference is loaded and run
   {do="fn::local_code:simple"},
   {do="log", msg="--------"},
   {do="fn::local_code:with_args", args=["blah", "bloo", "blee"]},
]
