# -*- mode:toml; -*-
[startup]
doot_version         = "1.1"
loaders              = { commands="default", task="default", parser="default" }
sources              = { tasks=["."], code=[] }
max_steps            = 100_000
skip_default_plugins = false
skip_plugin_search   = false

[startup.plugins]
# Allows for defining aliases
command        = { tasks="doot.cmds.list_cmd:ListCmd" }

[shutdown]
notify           = { speak=false } # success_msg="", fail_msg=""
defaulted_values = { write=false, path=".defaulted_values.toml" }

[settings.commands]
[settings.commands.run]
tracker      = "default"
runner       = "default"
reporter     = "default"
show         = false
report-line  = []

[settings.commands.list]
hide  = []

[logging]
# Standard loggers. See LoggerSpec.
stream  = { level="WARN", filter=[],  target="stdout",   format="{levelname:<8} : {message}"  }
file    = true
printer = { level="INFO", colour=true, target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }

[[locations]]
