# -*- mode:toml; -*-

[startup]
doot_version          = "1.1"
loaders               = { commands="default", task="default", parser="default" }
sources               = { tasks=[".tasks"], code=[] }
empty_cmd             = ["run", "example::+.matcher"]

[logging]
file = false

[logging.stream]
level   = "user"
filter  = []
target  = "stdout"
format  ="{levelname:<8}  : {message}"

[logging.printer]
level         = "WARNING"
colour        = true
target        = ["stdout"]
format        = "{message}"
filename_fmt  = "doot_printed.log"


[[tasks.example]]
name        = "+.matcher"
doc         = ["uses the match action to assign data to different subtasks"]
data        = ["a.bib", "b.txt", "c.bib", "d.py", "blah.bloo"]
inject_vals = {literal=["fpath"]}
actions     = [
    {do="log", msg="Generating Matched Subtasks"},
    {do="dootle.jobs.expand:MatchExpansionAction", mapping_="matrix", update_="subtasks", from_="data", inject_="inject_vals"},
    {do="dootle.jobs.expand:JobQueueAction",  from_="subtasks"},
    {do="log", msg="--------------------------"},
]
head-actions = [{do="log", msg="Job Head"}]

[tasks.example.matrix]
# The mapping from data suffix -> subtask name
".bib"  = "mapped::_.bib.task"
".txt"  = "mapped::_.txt.task"
"_"     = "mapped::_.fallback.task"

[[tasks.mapped]]
name = "_.bib.task"
actions = [
    {do="log", msg="A subtask: {_task_name}"},
    {do="log", msg="A .bib task for: {fpath}"},
    {do="log", msg="--------------------------"},
]

[[tasks.mapped]]
name = "_.txt.task"
actions = [
    {do="log", msg="A subtask: {_task_name}"},
    {do="log", msg="A .txt task for : {fpath}"},
    {do="log", msg="--------------------------"},
]

[[tasks.mapped]]
name = "_.fallback.task"
actions = [
    {do="log", msg="A subtask: {_task_name}"},
    {do="log", msg="A misc task for: {fpath}"},
    {do="log", msg="--------------------------"},
]
