# -*- mode:toml; -*-
[startup]
doot_version         = "0.13"
loaders              = { commands="default", task="default", parser="default" }
location_check       = { make_missing=true }
sources              = { tasks=[".tasks"], code=[] }
sleep                = { task=0.2, subtask=1, batch=1 }
max_steps            = 100_000
skip_default_plugins = false
skip_plugin_search   = false
empty_cmd            = "list"
implicit_task_cmd    = "run"
# default_task       = ""
# constants_file     = ""
# aliases_file       = ""

[startup.plugins]
# Allows for defining aliases
command        = { }

[shutdown]
notify           = { speak=false } # success_msg="", fail_msg=""
defaulted_values = { write=false, path=".defaulted_values.toml" }

[settings.commands]
[settings.commands.run]
tracker     = "default"
runner      = "default"
reporter    = "default"
report-line = []
aliases = {basic=["basic::basic"]}

[settings.commands.list]
hide    = []
# Alias { name=[args] }
aliases = { tasks=[], acts=["--actions"], printers=["--loggers"] }

[logging]
# Standard loggers. See jgdv.logging.LoggerSpec.
# Additional Level aliases: detail=debug, trace=info, user=warning
stream  = { level="user",   filter=[],             target="stdout", format="{levelname:<8} : {message}"  }
file    = false
printer = { level="NOTSET", colour=true,           target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }

[logging.subprinters]
default       = {level="user"}
cmd           = {level="user",  colour="cyan"}
task_header   = {level="user",  colour="magenta"}
task          = {level="user",  colour="white"}
action_exec   = {level="user",  colour="cyan"}


[[tasks.basic]]
name = "basic"
actions = [{do="log", msg="Look at the settings.commands sections"}]
