# -*- mode:toml; -*-
[startup]
doot_version  = "1.1"
loaders       = { commands="default", task="default", parser="default" }
sources       = { tasks=[".tasks"], code=[] }
empty_cmd     = ["simplealias"]
implicit_cmd  = []

[startup.plugins]
# Allows for defining aliases
command        = {}

[settings.commands]
[settings.commands.list]
hide    = []
# Alias { name=[args] } -> doot name -> doot list args
aliases = { simplealias=["--help"] }

[logging]
# Standard loggers. See jgdv.logging.LoggerSpec.
# Additional Level aliases: detail=debug, trace=info, user=warning
stream  = { level="user",   filter=[],   target="stdout", format="{levelname:<8} : {message}"  }
file    = false
printer = { level="NOTSET", colour=true, target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }
