# -*- mode:toml; -*-
[startup]
doot_version  = "1.1"
loaders       = { commands="default", task="default", parser="default" }
sources       = { tasks=[".tasks"], code=[] }
empty_cmd     = ["simplealias"]
implicit_cmd  = []

[startup.plugins]
command        = {}

[settings.commands]
[settings.commands.list]
# Alias { name=[args] } -> doot name -> doot list args
hide    = []
aliases = { simplealias=["--help"] }

[logging]
stream  = { level="WARNING",   filter=[],   target="stdout", format="{levelname:<8} : {message}"  }
file    = false
printer = { level="NOTSET", colour=true, target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }
