# -*- mode:toml; -*-
[startup]
doot_version         = "1.1"
loaders              = { commands="default", task="default", parser="default" }
sources              = { tasks=[".tasks"], code=["."] }
skip_default_plugins = false
skip_plugin_search   = false

[startup.plugins]
# Allows for defining aliases
command  = { tasks="doot.cmds.list_cmd:ListCmd"}

[shutdown]
notify            = { speak=false }  # success_msg="", fail_msg=""
defaulted_values  = { write=false, path=".defaulted_values.toml" }

[settings.commands]
[settings.commands.run]
tracker     = "default"
runner      = "default"
reporter    = "default"
report-line = []

[settings.commands.list]
hide     = []
aliases  = { tasks=[] }

[logging]
# Standard loggers. See jgdv.logging.LoggerSpec.
# Additional Level aliases: detail=debug, trace=info, user=warning
stream  = { level="user",   filter=[],             target="stdout", format="{levelname:<8} : {message}"  }
file    = false
printer = { level="NOTSET", colour=true,           target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }

[tasks]

[[tasks.example]]
name = "top"
doc = [
"The doot.toml dict startup.sources lets customize where tasks are loaded from,",
"and where local code is loaded from.",
"in this case, code is loaded from cwd."
]
depends-on = ["example::local.task", "example::local.action",]

[[tasks.example]]
name     = "local.task"
ctor     = "cls::local_code:SimpleTaskExample"  
doc      = [
   "A Task demonstrating a custom local task",
   "that adds a head and tail automatically",
] 
actions  = [
   {do="log", msg="blah"}
]

[[tasks.example]]
name                 = "local.action"
doc                  = ["An example of importing local code for an action"] 
actions              = [
   { do="fn::local_code:simple"},
]
