# -*- mode:toml; -*-
# This demonstrates injecting values into dependencies.
# Injections can occur in a number of ways:
# 1: from spec, which uses values expanded from the task spec currently running
# 2: from state, which uses values of the current task state.
# 3: from target, which uses values from the target subtask, when it runs
# 4: literal, which injects values as written

[startup]
doot_version  = "1.1"
loaders       = { commands="default", task="default", parser="default" }
sources       = { tasks=[".tasks"], code=[] }
empty_cmd     = ["run", "inject::top"]

[settings.commands]
[logging]
file = false
[logging.stream]
level = "WARNING"
filter = ["jgdv"]
target = "stdout"
format="{levelname:<8} : {message}"

[logging.printer]
level        = "WARNING"
colour       = true
target       = ["stdout"]
format       = "{message}"
filename_fmt = "doot_printed.log"

[[tasks.inject]]
name        = "top"
prefix      = "top"
blah        = "inject::top spec's direct value"
bloo        = "{aweg}"
aweg        = "{blee}"
blee        = "Immediate Expansion in inject::top"
depends_on  = [
    {task="inject::_.target"},
    # # Source expansion:  blah -> expanded(blah)
    {task="inject::_.target", inject={from_spec=["blah"]}},
    # # Source remapping:  blah -> expanded(bloo)
    {task="inject::_.target", inject={from_spec={blah="{bloo}"}}},
    # # Target remapping:  blah -> l1(bloo_) -> aweg -> expanded(aweg, source=inject::_.target)
    {task="inject::_.target", inject={from_target={blah="{bloo}"}}},
    # # Literal insertion: blah -> 'a direct insertion'
    {task="inject::_.target", inject={literal={blah="literal insertion"}}},
    # # Literal insertion with keys: blah -> 'literal with key: {other}' -
    {task="inject::_.target", inject={literal={blah="literal with key: {other}"}}},
]

[[tasks.inject]]
name        = "_.target"
doc         = [
    "When run on its own, will message 'default blah'.",
    "When run from inject::top, will message values based on the injection.",
]
prefix   = "sub"
blah     = "inject::_.target's default value"
aweg     = "inject::_target's Late Expansion"
other    = "other"
info     = "A default info message"
actions  = [
    # Log action format: {do="log", msg="{info}"},
    {do="log", msg="The Value of blah is: {blah}"},
    {do="log", msg="--------------------------"},
]
