# -*- mode:toml; -*-
[startup]
doot_version  = "1.1"
loaders       = { commands="default", task="default", parser="default" }
sources       = { tasks=[".tasks"], code=["."] }
empty_cmd     = ["run", "example::custom.task"]

[logging]
# Standard loggers. See jgdv.logging.LoggerSpec.
# Additional Level aliases: detail=debug, trace=info, user=warning
stream  = { level="user",   filter=[],             target="stdout", format="{levelname:<8} : {message}"  }
file    = false
printer = { level="WARNING", colour=true,           target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }

[tasks]

[[tasks.example]]
name     = "custom.task"
# By specifying the ctor (a jgdv coderef), that is loaded and used instead of a default doot task
ctor     = "cls::local_code:SimpleTaskExample"  
doc      = [
   "A Task demonstrating a custom local task",
   "that adds a head and tail automatically",
] 
actions  = [
   {do="log", msg="An action specified in the doot.toml"}
]
