# -*- mode:toml; -*-
[startup]
doot_version         = "0.13"
loaders              = { commands="default", task="default", parser="default" }
location_check       = { make_missing=true }
sources              = { tasks=["."], code=[] }
sleep                = { task=0.2, subtask=1, batch=1 }
max_steps            = 100_000
skip_default_plugins = false
skip_plugin_search   = false
empty_cmd            = "list"
implicit_task_cmd    = "run"
# default_task       = ""
# constants_file     = ""
# aliases_file       = ""

[startup.plugins]
# Allows for defining aliases
command        = { tasks="doot.cmds.list_cmd:ListCmd" }

[shutdown]
notify           = { speak=false } # success_msg="", fail_msg=""
defaulted_values = { write=false, path=".defaulted_values.toml" }

[settings.commands]
[settings.commands.run]
tracker     = "default"
runner      = "default"
reporter    = "default"
report-line = []

[settings.commands.list]
hide = []

[logging]
# Standard loggers. See LoggerSpec.
stream  = { level="WARNING", filter=[],             target="stdout",   format="{levelname:<8} : {message}"  }
file    = false
printer = { level="NOTSET", colour=true,            target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }

[logging.subprinters]
default       = {level="user"}
cmd           = {level="user",  colour="cyan"}
task_header   = {level="user",  colour="magenta"}
task          = {level="user",  colour="white"}
action_exec   = {level="user",  colour="cyan"}

[[locations]]

[[tasks.predicates]]
name       = "top"
doc        = ["Runs 2 tasks: yes, and no. yes passes a predicate, no fails it. "]
depends-on = ["predicates::yes", "predicates::no"]

[[tasks.predicates]]
name       = "yes"
f_target     = "doot.toml"
depends-on = [
{do="log", msg="Task will run because {f_target} exists"},
{do="exists?", args=["{f_target}"]}
]
actions    = [{do="log", msg="Predicate success" }]

[[tasks.predicates]]
name       = "no"
f_target     = "not.toml"
depends-on = [
{do="log", msg="Will Skip because {f_target} does not exist"},
{do="exists?", args=["{f_target}"]}
]
actions    = [{do="log", msg="This shouldn't run"}]
