# -*- mode:toml; -*-
[startup]
doot_version         = "1.1"
loaders              = { commands="default", task="default", parser="default" }
sources              = { tasks=["."], code=[] }
skip_default_plugins = false
skip_plugin_search   = false

[startup.plugins]
# Allows for defining aliases
command        = { tasks="doot.cmds.list_cmd:ListCmd" }

[shutdown]
notify           = { speak=false } # success_msg="", fail_msg=""
defaulted_values = { write=false, path=".defaulted_values.toml" }

[settings.commands]
[settings.commands.run]
tracker     = "default"
runner      = "default"
reporter    = "default"
report-line = []

[settings.commands.list]
hide = []

[logging]
# Standard loggers. See LoggerSpec.
stream  = { level="WARNING", filter=[],             target="stdout",   format="{levelname:<7} : {message}"  }
file    = false
printer = { level="INFO", colour=true,            target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }

[[locations]]

[[tasks.predicates]]
name        = "top"
doc         = ["Runs 2 tasks: yes, and no. yes passes a predicate, no fails it. "]
depends-on  = ["predicates::yes", "predicates::no"]

[[tasks.predicates]]
name        = "yes"
f_target    = "doot.toml"
depends-on  = [
    {do="log", msg="Task will run because {f_target} exists. 'predicate success' should be logged."},
    {do="exists?", args=["{f_target}"]}
]
actions    = [ {do="log", msg="Predicate success" } ]

[[tasks.predicates]]
name        = "no"
f_target    = "not.toml"
depends-on  = [
    {do="log", msg="Will Skip because {f_target} does not exist. 'predicate failure' should *not* be logged."},
    {do="exists?", args=["{f_target}"]}
]
actions    = [ {do="log", msg="Predicate failure"} ]
