# -*- mode:toml; -*-

[startup]
doot_version  = "1.1"
loaders       = { commands="default", task="default", parser="default" }
sources       = { tasks=["."], code=[] }
empty_cmd     = ["run", "predicates::top"]

[logging]
# Standard loggers. See LoggerSpec.
stream  = { level="WARNING", filter=[],             target="stdout",   format="{levelname:<7} : {message}"  }
file    = false
printer = { level="WARNING", colour=true,            target=["stdout"], format="{message}", filename_fmt="doot_printed.log" }

[[tasks.predicates]]
name        = "top"
doc         = ["Runs 2 tasks: yes, and no. yes passes a predicate, no fails it. "]
depends-on  = ["predicates::_.yes", "predicates::_.no"]

[[tasks.predicates]]
name        = "_.yes"
prefix      = "should.succeed"
f_target    = "doot.toml"
depends-on  = [
    {do="log", msg="----------------"},
    {do="log", msg="Success Example:"},
    {do="log", msg="Task will run because {f_target} exists. 'predicate success' should be logged:"},
    # The predicate:
    {do="exists?", args=["{f_target}"]}
]
actions    = [ {do="log", msg="Predicate success" } ]

[[tasks.predicates]]
name        = "_.no"
prefix      = "should.fail"
f_target    = "not.toml"
depends-on  = [
    {do="log", msg="----------------"},
    {do="log", msg="Failure Example:"},
    {do="log", msg="Will Skip because {f_target} does not exist. 'predicate failure' should *not* be logged:"},
    # The Predicate:
    {do="exists?", args=["{f_target}"]}
]
actions  = [ {do="log", msg="Predicate failure"} ]
cleanup  = [ {do="log", msg="----------------"}  ]
